### ISSUE TITLE
Set up GitHub Pages for demo

### ISSUE THREAD

**Issue by francislavoie** [contributte/anabelle#9]
https://pages.github.com/

Kinda a chore to clone it or use another tool to see what the output looks like.

Short term, https://htmlpreview.github.io/?https://github.com/ublaboo/anabelle/blob/master/demo/index.html works though.

**Comment by paveljanda** [comment]
Thanks for the idea, done :) https://ublaboo.github.io/anabelle

Link added also to the README.

**Comment by francislavoie** [comment]
@paveljanda doesn't looks like it's actually in the README though. It's nowhere to find in https://github.com/ublaboo/anabelle/blob/master/README.md

**Comment by paveljanda** [comment]
Right, cherry-picked wrong commit. It's there finally.
Thanks for the feedback.
